-- ─── Community Specs Table ───────────────────────────────────────────────────
-- Stores /ai specs auto-generated by MCP agents for sites that don't have
-- their own /ai endpoint. Enables the 3-step discovery fallback:
--   1. Direct /ai fetch
--   2. Community registry lookup (this table)
--   3. Agent generates → POSTs here

CREATE TABLE community_specs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Target site
  url           TEXT NOT NULL UNIQUE,
  domain        TEXT NOT NULL,

  -- /ai spec data
  ai_spec       JSONB NOT NULL,
  confidence    INTEGER NOT NULL DEFAULT 0
                CHECK (confidence >= 0 AND confidence <= 100),

  -- Metadata
  contributors  INTEGER NOT NULL DEFAULT 1,
  source_hints  JSONB,
  ttl           INTEGER NOT NULL DEFAULT 604800,

  -- Status
  status        TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'expired', 'superseded', 'blocked')),
  claimed       BOOLEAN NOT NULL DEFAULT false,
  claimed_at    TIMESTAMPTZ,

  -- Link to owner-registered service (if claimed)
  service_id    UUID REFERENCES services(id) ON DELETE SET NULL
);

-- Indexes
CREATE INDEX idx_community_specs_url        ON community_specs (url);
CREATE INDEX idx_community_specs_domain     ON community_specs (domain);
CREATE INDEX idx_community_specs_status     ON community_specs (status);
CREATE INDEX idx_community_specs_confidence ON community_specs (confidence DESC);

-- ─── Add source column to services table ────────────────────────────────────
ALTER TABLE services ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'owner'
  CHECK (source IN ('owner', 'community', 'auto'));
